-
  name: create new file with content
  hosts: server1
  become: yes
  tasks:
    - name: create file with content
      copy:
        dest: "/home/ec2-user/gcloud/gcloud.txt"
        content:
          [google-cloud-sdk]
            name=Google Cloud SDK
            baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
            enabled=1
            gpgcheck=1
            repo_gpgcheck=1
            gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                   https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
