-
  name: install jenkins
  hosts: server1
  become: yes
  tasks:
    - name: Yum Install Packages
      yum: name={{item}} state=present
      with_items:
         - wget
    - name: create folder jenkins-test
      file:
        path: /home/ec2-user/jenkins-test
        state: directory

    - name: jenkins install
      get_url:
        url: http://mirrors.jenkins.io/war-stable/2.204.6/jenkins.war
        dest: /home/ec2-user/jenkins-test
        

    - name: run war file
      command: java -jar jenkins.war chdir=/home/ec2-user/jenkins-test

    - name: sleep for 30 seconds and continue with play
      wait_for: timeout=30
      delegate_to: server1

    - name: init password jenkin
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: print init password jenkins
      debug:
        var: result.stdout
