-
  name: set java path
  hosts: server1
  become: yes
  vars:
    environment:
      JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.amzn2.0.1.x86_64
  tasks:
    name: set path
    command: export JAVA_HOME=$JAVA_HOME && export PATH=$PATH:$JAVA_HOME
